### ISSUE TITLE
TypeError: Cannot read property 'minify' of null

### ISSUE THREAD

**Issue by natew** [Rich-Harris/butternut#123]
Node 6.9.3
Webpack 2

Getting this when using webpack butternut plugin:

```
> my-web-app@ build /Users/nw/projects/motion/starter/apps/web
> node scripts/build.js

running webpack for: production
/Users/nw/projects/motion/starter/apps/web/node_modules/butternut/dist/butternut.cjs.js:1662
				this.alternate.minify( code );
				              ^

TypeError: Cannot read property 'minify' of null
    at IfStatement.minify (/Users/nw/projects/motion/starter/apps/web/node_modules/butternut/dist/butternut.cjs.js:1662:19)
    at /Users/nw/projects/motion/starter/apps/web/node_modules/butternut/dist/butternut.cjs.js:2431:14
    at Array.forEach (native)
    at SwitchCase.minify (/Users/nw/projects/motion/starter/apps/web/node_modules/butternut/dist/butternut.cjs.js:2430:19)
    at SwitchStatement.minify (/Users/nw/projects/motion/starter/apps/web/node_modules/butternut/dist/butternut.cjs.js:147:33)
    at SwitchStatement.minify (/Users/nw/projects/motion/starter/apps/web/node_modules/butternut/dist/butternut.cjs.js:2478:28)
    at /Users/nw/projects/motion/starter/apps/web/node_modules/butternut/dist/butternut.cjs.js:3115:14
    at Array.forEach (native)
    at BlockStatement.minify (/Users/nw/projects/motion/starter/apps/web/node_modules/butternut/dist/butternut.cjs.js:3114:14)
    at ForStatement.minify (/Users/nw/projects/motion/starter/apps/web/node_modules/butternut/dist/butternut.cjs.js:150:11)
    at ForStatement.minify (/Users/nw/projects/motion/starter/apps/web/node_modules/butternut/dist/butternut.cjs.js:1232:28)
    at ForStatement.minify (/Users/nw/projects/motion/starter/apps/web/node_modules/butternut/dist/butternut.cjs.js:1277:37)
    at /Users/nw/projects/motion/starter/apps/web/node_modules/butternut/dist/butternut.cjs.js:3115:14
    at Array.forEach (native)
    at BlockStatement.minify (/Users/nw/projects/motion/starter/apps/web/node_modules/butternut/dist/butternut.cjs.js:3114:14)
    at FunctionExpression.minify (/Users/nw/projects/motion/starter/apps/web/node_modules/butternut/dist/butternut.cjs.js:150:11)
```

**Comment by Rich-Harris** [comment]
Thanks — do you know what input code is causing that? Any chance you can reproduce it on https://butternut.now.sh ? 

Also, what version of Butternut do you have installed?

```bash
cat node_modules/butternut/package.json  | grep version
```

**Comment by natew** [comment]
Version is 0.3.6, the stack is pretty large, 10Mb unminified. Any best way to help you debug that?

Also, used Babili and it works fine with this bundle.

**Comment by Rich-Harris** [comment]
Any way you can share the input code? I should be able to figure out what's causing the error from that.

**Comment by DylanPiercey** [comment]
@Rich-Harris I ran into the same issue using the webpack plugin for my client side build (works fine for my server side build).

Here is a gist which contains triggers the error (most of the bundle is included sorry! :p).
https://gist.github.com/DylanPiercey/4eb46f943d8e06a56802bf50937e77f0

**Comment by novemberborn** [comment]
Per https://github.com/Apercu/butternut-webpack-plugin/issues/4 this happens when `NODE_ENV` is `"production"`, which implies Butternut is struggling with code that webpack has already optimized a little.

I think the error comes from https://github.com/Rich-Harris/butternut/blob/f3e7627d6313c7e70973f9ac0b16e22403fc733c/src/program/types/IfStatement.js#L110:L111 which handles `if (false) {}` cases. I'm not quite sure what `this.alternate` refers to, but I assume it may be an `else` branch? In that case it's not safe to assume `this.alternate` exists.

This may be a patch:

```js
			} else { // if ( false ) {...}
				if (this.alternate) {
					this.alternate.minify( code );
					code.remove( this.start, this.alternate.start );
				} else {
					code.remove( this.start, this.end );
				}
			}
```

But I don't know if I'm reading the code right. With that patch I do get output but there is a syntax error. I'm not sure if that's a separate bug.

**Comment by RReverser** [comment]
@Rich-Harris Also just ran into this trying to swap UglifyJS to Babili. Do you need more repro cases?
