### ISSUE TITLE
Bug: ++Incrementing in expressions

### ISSUE THREAD

**Issue by Loilo** [Rich-Harris/butternut#133]
From trying to squash minified [atmosphere](https://cdnjs.cloudflare.com/ajax/libs/atmosphere/2.2.9/atmosphere.min.js).

In the following example, Butternut removes the parantheses around the incrementation without any compensation, resulting in three subsequent `+` characters.

**Input:**
```javascript
"any_string" +(++any_var)
```

**Output Butternut:**
```javascript
"any_string" +++any_var
```

**Output UglifyJS:**
```javascript
"any_string"+ ++any_var;
```

Another issue will occur when the incremented value is not a variable but a string/number literal.

**Input:**
```javascript
"any_string" +(++1)
```

**Error Butternut:**
```
SyntaxError: Assigning to rvalue (1:17)
    at Parser.pp$4.raise (/path/to/project/node_modules/acorn/dist/acorn.js:2549:13)
    at Parser.pp$2.checkLVal (/path/to/project/node_modules/acorn/dist/acorn.js:1690:10)
    at Parser.pp$3.parseMaybeUnary (/path/to/project/node_modules/acorn/dist/acorn.js:1899:22)
    at Parser.pp$3.parseExprOps (/path/to/project/node_modules/acorn/dist/acorn.js:1848:19)
    at Parser.pp$3.parseMaybeConditional (/path/to/project/node_modules/acorn/dist/acorn.js:1831:19)
    at Parser.pp$3.parseMaybeAssign (/path/to/project/node_modules/acorn/dist/acorn.js:1806:19)
    at Parser.pp$3.parseParenAndDistinguishExpression (/path/to/project/node_modules/acorn/dist/acorn.js:2113:30)
    at Parser.pp$3.parseExprAtom (/path/to/project/node_modules/acorn/dist/acorn.js:2035:41)
    at Parser.pp$3.parseExprSubscripts (/path/to/project/node_modules/acorn/dist/acorn.js:1929:19)
    at Parser.pp$3.parseMaybeUnary (/path/to/project/node_modules/acorn/dist/acorn.js:1906:17)
```

**Output UglifyJS:**
```javascript
"any_string"+ ++1;
```

Side note: The whitespace *before*  the concatenating `+` is also kept in output. It could safely be removed for a slightly better result.

**Comment by Rich-Harris** [comment]
Thanks — it was doing an overly naive check to see if it needed to overwrite the operator or not.

`"any_string" +(++1)` isn't valid JS, which is why Acorn fails to parse it in the first place — not actually a bug on Butternut's part. Uglify's parser is being a little bit too lenient here, but I don't think it's really at fault since the code would never have run in the first place (@kzc let me know if you want me to raise an issue anyway, don't know what your stance is on things like that).

**Comment by Loilo** [comment]
Mh, I actually didn't realize that. So this is in fact a bug in the concerning library in the first place ([see here](https://github.com/Atmosphere/atmosphere-javascript/blob/master/modules/javascript/src/main/webapp/javascript/atmosphere.js#L1066)).

Well, then Butternut's behaviour is fine I guess.

**Comment by kzc** [comment]
> Uglify's parser is being a little bit too lenient here, but I don't think it's really at fault since the code would never have run in the first place

Garbage in/garbage out is fine as long as it preserves the error in the original code.

**Comment by kzc** [comment]
@Loilo Recent versions of uglify trap this error:
```
$ bin/uglifyjs -V
uglify-js 3.0.8

$ echo '"any_string" +(++1)' | bin/uglifyjs
Parse error at 0:1,15
"any_string" +(++1)
               ^
ERROR: Invalid use of ++ operator
```

**Comment by Loilo** [comment]
Hum. Then I should probably stop [using version 2](https://skalman.github.io/UglifyJS-online/) for reference.

**Comment by kzc** [comment]
There are still back ports of bug fixes to from 3.x to 2.x. But that third party online tool could be using a very old version of uglify.
