### ISSUE TITLE
Can't catch undefined

### ISSUE THREAD

**Issue by liamwhite** [Rich-Harris/butternut#177]
I'm not even sure if this is valid JavaScript, but browsers and node seem just fine with executing this:
```js
// test.js
try {
  foobar();
} catch(undefined) {
}
```

```
$ squash test.js
The final argument to magicString.overwrite(...) should be an options object. See https://github.com/rich-harris/magic-string
Cannot read property 'contains' of undefined
TypeError: Cannot read property 'contains' of undefined
    at Identifier.getValue (/usr/lib/node_modules/butternut/dist/butternut.cjs.js:1785:20)
    at Identifier.minify (/usr/lib/node_modules/butternut/dist/butternut.cjs.js:1828:20)
    at CatchClause.minify (/usr/lib/node_modules/butternut/dist/butternut.cjs.js:240:11)
    at CatchClause.minify (/usr/lib/node_modules/butternut/dist/butternut.cjs.js:1084:28)
    at TryStatement.minify (/usr/lib/node_modules/butternut/dist/butternut.cjs.js:240:11)
    at TryStatement.minify (/usr/lib/node_modules/butternut/dist/butternut.cjs.js:3146:28)
    at BlockStatement.minify (/usr/lib/node_modules/butternut/dist/butternut.cjs.js:3784:15)
    at Object.Program (/usr/lib/node_modules/butternut/dist/butternut.cjs.js:4042:12)
    at Object.squash (/usr/lib/node_modules/butternut/dist/butternut.cjs.js:4114:9)
    at compileFile (/usr/lib/node_modules/butternut/bin/runButternut.js:51:25)
```

Found in the wild [here](https://github.com/liudangyi/jquery-ujs/blob/4605991/dist/rails.js#L230) (and generated by [this](https://github.com/liudangyi/jquery-ujs/blob/4605991/src/utils/ajax.coffee#L65) line).

**Comment by nifgraup** [comment]
It's valid: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/undefined
> While it is possible to use it as an identifier (variable name) in any scope other than the global scope (because undefined is not a reserved word), doing so is a very bad idea that will make your code difficult to maintain and debug.
